//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitaphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCHECK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLCHECK()
        {
            this.TBLKITAP = new HashSet<TBLKITAP>();
        }
    
        public int checkid { get; set; }
        public Nullable<int> islemkisi { get; set; }
        public Nullable<System.DateTime> islemtarih { get; set; }
    
        public virtual TBLKISILER TBLKISILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLKITAP> TBLKITAP { get; set; }
    }
}
