//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitaphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKISILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKISILER()
        {
            this.TBLCHECK = new HashSet<TBLCHECK>();
        }
    
        public int kisiid { get; set; }
        public string kisiad { get; set; }
        public string kisisoyad { get; set; }
        public Nullable<int> kisitc { get; set; }
        public string kisitelno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCHECK> TBLCHECK { get; set; }
    }
}
