//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitaphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKITAP
    {
        public int kitapid { get; set; }
        public string kitapad { get; set; }
        public Nullable<int> kitapisbn { get; set; }
        public Nullable<int> kitapyil { get; set; }
        public Nullable<decimal> kitapfiyat { get; set; }
        public string kitapcheck { get; set; }
        public Nullable<short> kitapkategori { get; set; }
        public string kitapresim { get; set; }
        public Nullable<int> kitapcheckid { get; set; }
    
        public virtual TBLCHECK TBLCHECK { get; set; }
        public virtual TBLKATEGORILER TBLKATEGORILER { get; set; }
    }
}
